repos:
  - repo: local
    hooks:
      - id: pre-commit-lint
        name: pre-commit-lint
        entry: deno lint
        language: system
        stages: [commit]
        pass_filenames: false
        types_or: [javascript, jsx, ts, tsx, json, markdown]
        verbose: true
      - id: pre-commit-fmt
        name: pre-commit-fmt
        entry: deno fmt
        language: system
        stages: [commit]
        pass_filenames: false
        types_or: [javascript, jsx, ts, tsx]
        verbose: true
